const connection = require('../utils/Connect')
const router = require('express').Router()
const fs = require('fs')
const PDFDocument = require('pdfkit');

const createPdf = (data) => {
    const doc = new PDFDocument();
    doc.fontSize(12).text(`${data.day}D | ${data.night}N`, {align:'center'})
    doc.moveDown(1)
    doc.fontSize(9).text(`CONFIRM ITINERARY`, {align:'center'})
    doc.moveDown(1)
    doc.fontSize(9).text(`${data.address}`, {align:'center'})
    doc.moveDown(3)
    doc.fontSize(20).text(data.tour_name.toUpperCase(), { align: 'center' });
    doc.moveDown(0.5)
    doc.fontSize(9).text(data.tour_des)
    doc.moveDown(2)
    doc.fontSize(17).text('Journey schedule', { align: 'center' })
    doc.moveDown(1)
    data.days.forEach((days, index)=> {
        doc.fontSize(12).text(`day ${index+1}`, 70)
        doc.moveDown()
        doc.fontSize(9).text(days.place_name, 130)
        doc.fontSize(8).text(days.place_des, 160)
        doc.moveDown()
        if(days.addon_name){
            doc.fontSize(9).text(days.addon_name, 130)
            doc.fontSize(8).text(days.addon_des, 160)
            doc.moveDown()
        }
        if(days.activity_name){
            doc.fontSize(9).text(days.activity_name, 130)
            doc.fontSize(8).text(days.activity_des, 160)
            doc.moveDown()
        }
    })
    doc.moveDown(4)
    doc.addPage()
    doc.fontSize(10).text(`Costumer name: ${data.customer_name}`, { align:'center '})
    doc.moveDown()
    doc.fontSize(10).text(`Costumer id: ${data.customer_id}`, { align:'center '})
    doc.moveDown()
    doc.fontSize(10).text(`Tour date id: ${data.tour_date}`, { align:'center '})
    doc.moveDown()
    doc.fontSize(10).text(`Adult (5 And Above 5 Years): ${data.adults}`, { align:'center '})
    doc.moveDown()
    doc.fontSize(10).text(`Executive Name: ${data.user_name}`, { align:'center '})
    doc.addPage()
    doc.fontSize(8).text(`HDFC BANK`)
    doc.moveDown()
    doc.fontSize(8).text(`Account Holder: TRIPPENS`)
    doc.moveDown()
    doc.fontSize(8).text(`Account Number: 50200065078880`)
    doc.moveDown()
    doc.fontSize(8).text(`IFSC: HDFC0000057`)
    doc.moveDown()
    doc.fontSize(8).text(`Branch: TRICHUR - PALACE ROAD`)
    doc.moveDown(3)
    doc.fontSize(8).text(`IDFC FIRST BANK`)
    doc.moveDown()
    doc.fontSize(8).text(`Account Holder: TRIPPENS`)
    doc.moveDown()
    doc.fontSize(8).text(`Account Number: 10084901004`)
    doc.moveDown()
    doc.fontSize(8).text(`IFSC: IDFB0080732`)
    doc.moveDown()
    doc.fontSize(8).text(`Branch: THRISSUR EAST FORT`)
    doc.moveDown(2)
    doc.fontSize(10).text(`PAYMENT POLICY`)
    doc.moveDown(2)
    doc.fontSize(8).text('-- A minimum payment is required for booking a tour - Non refundable', 100)
    doc.fontSize(8).fillColor('red').text('(The minimum payment will vary depending on the tour)', 100)
    doc.moveDown()
    doc.fontSize(8).fillColor('black').text('-- 21-35 Days before date of departure : 50% of Cost 20 Days before date of departure : 100% of Total cost', 100)
    doc.moveDown(2)
    doc.fontSize(10).text('CANCELLATION & REFUND POLICY', 70)
    doc.moveDown(2)
    doc.fontSize(8).text('60 Days & Prior to Arrival POLICY - 25% of the Tour/Service Cost.')
    doc.moveDown()
    doc.fontSize(8).text('59 Days to 30 Days Prior To Arrival - 50% of the Tour/Service Cost.')
    doc.moveDown()
    doc.fontSize(8).text('29 Days to 15 Days Prior To Arrival - 75% of the Tour/Service Cost.')
    doc.moveDown()
    doc.fontSize(8).text('14 Days and less Prior To Arrival – No refund')
    doc.moveDown()
    doc.fontSize(8).text('Transportation and accommodation are as per itinerary only, if you have to change any of the same we will not be responsible for any kind of refund.')
    doc.moveDown()
    doc.fontSize(8).text('There will be no refund for add-ons.')
    doc.moveDown(2)
    doc.fontSize(10).text('INCLUSIONS')
    doc.moveDown()
    doc.fontSize(8).text('Pick up & Drop off')
    doc.moveDown()
    doc.fontSize(8).text('All Local Transport ')
    doc.moveDown()
    doc.fontSize(8).text('Local Sight seeing ')
    doc.moveDown()
    doc.fontSize(8).text('Accommodation')
    doc.moveDown(2)
    doc.fontSize(10).text('EXCLUSIONS')
    doc.moveDown()
    doc.fontSize(8).text('Food')
    doc.moveDown()
    doc.fontSize(8).text('Entry Ticket')
    doc.moveDown()
    doc.fontSize(8).text('GST')
    doc.addPage()
    doc.fontSize(12).text(`TERMS & CONDITIONS`, {align:'center'})
    doc.moveDown()
    doc.fontSize(8).text(`1. if you're not able to reach out the destination on time. That is not our responsibility`)
    doc.moveDown()
    doc.fontSize(8).text(`2. Hotel Check in time - 11.30 a.m. & checkout - 10.00 am.`)
    doc.moveDown()
    doc.fontSize(8).text(`3. The booking stands liable to be cancelled if 100% payment is not received less than 20 days before date of departure. If the trip is cancel due to this reason advance will not be refundable. If you are not pay the amount that in mentioned in payment policy then tour will be cancel.`)
    doc.moveDown()
    doc.fontSize(8).text(`5. All activities which are not mentioned in the above itinerary such as visiting additional spots or involving in paid activities, If arranging separate cab etc. is not included in this`)
    doc.moveDown()
    doc.fontSize(8).text(`6. In case of using additional transport will be chargeable. `)
    doc.moveDown()
    doc.fontSize(8).text(`7. All transport on the tour will be grouped together. Anyone who deviates from it will be excluded from this package. `)
    doc.moveDown()
    doc.fontSize(8).text(`8. The company has the right for expelling persons who disagree with passengers or misrepresent the company during the trip.  `)
    doc.moveDown()
    doc.fontSize(8).text(`9. The company does not allow passengers to give tips to the driver for going additional spots. `)
    doc.moveDown()
    doc.fontSize(8).text(`10. In case of cancellation due to any reason such as Covid, strike, problems on the part of railways, malfunctions, natural calamities etc., package amount will not be refunded.`)
    doc.moveDown()
    doc.fontSize(8).text(`11. The Company will not be liable for any confirmation of train tickets, flight tickets, other transportation or any other related items not included in the package.`)
    doc.moveDown()
    doc.fontSize(8).text(`12. In Case Of Events And Circumstances Beyond Our Control, We Reserve The Right To Change All Or Parts Of The Contents Of The Itinerary For Safety And Well Being Of Our Esteemed Passengers.`)
    doc.moveDown()
    doc.fontSize(8).text(`13. Bathroom Facility | Indian or European`)
    doc.moveDown()
    doc.fontSize(8).text(`14. In season rooms will not be the same as per itinerary but category will be the same (Budget economy). `)
    doc.moveDown()
    doc.fontSize(8).text(`15. Charge will be the same from the age of 5 years`)
    doc.moveDown()
    doc.fontSize(8).text(`16. We are not providing tourist guide, if you are taking their service in your own cost we will not be responsible for the same.`)
    doc.moveDown()
    doc.fontSize(8).text(`17. You should reach to departing place on time, also you should keep the time management or you will not be able to cover all the place.`)
    doc.moveDown()
    doc.fontSize(8).text(`18. If the climate condition affect the sightseeing that mentioned in itinerary, then we won’t provide you the additional spots apart from the itinerary. `)
    doc.moveDown()
    doc.fontSize(8).text(`19. Transportation timing 8 am to 6 pm, if use vehicle after that then cost will be extra`)
    doc.moveDown()
    doc.fontSize(8).text(`20. Will visit places as per itinerary only, if you visit other than this then cost will be extra `)
    doc.moveDown()
    doc.fontSize(8).text(`21. If any customers misbehave with our staffs improperly then we will cancel his tour immediately and after that he can't continue with this tour.`)
    doc.moveDown()
    doc.fontSize(8).text(`22. If the trip is not fully booked or cancelled due to any special circumstances, we will postpone the trip to another day. Otherwise, if the journey is to be done on the pre-arranged day, the customers will have to bear the extra money themselves. `)
    doc.moveDown()
    doc.fontSize(8).text(`23. If you have any problems with the tour, please notify us as soon as possible so that we can resolve the problem. If you raise the issue after the tour, we will not be able to help you.`)
    doc.moveDown()
    doc.fontSize(8).text(`24. Our company does not provide specific seats on the Volvo bus, if you need a seat particularly, please let the executive know during the confirmation of your reservation. (Requires additional payment). `)
    doc.moveDown()
    doc.end();
    return doc
}

router.post('/', (req, res)=> {
    const data = req.body;
    if(data.tour_name && data.tour_des && data.days && data.day && data.night && data.address && data.customer_name && data.customer_id && data.tour_date && data.adults && data.user_name){
        const doc=createPdf(data)
        res.setHeader('Content-Disposition', 'attachment; filename="file.pdf"');
        res.setHeader('Content-Type', 'application/pdf');
        doc.pipe(res);
    }
    else{
        res.status(400).json({
            result: "itenerary creation failed",
            success: false
        })
    }
})

module.exports = router;